[project]
name = "nvl-widget"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anywidget>=0.9.21",
    "pandas>=3.0.0",
    "pydantic>=2.12.5",
    "traitlets>=5.14.3",
]

[dependency-groups]
dev = [
    "marimo>=0.19.4",
    "pre-commit>=4.5.1",
    "ruff>=0.14.13",
]

[tool.marimo.runtime]
pythonpath = ["src"]
